// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbY-0GqHkKardiRV4nImYMYA55lWjLQ9I',
    appId: '1:642502995428:web:84b7bb8d1af067fb686bf1',
    messagingSenderId: '642502995428',
    projectId: 'full-crud-application',
    authDomain: 'full-crud-application.firebaseapp.com',
    storageBucket: 'full-crud-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqw3Ig861RWUWMBNS_oHXKym_ww-Bapg',
    appId: '1:642502995428:android:ea42f7966bc2c9ff686bf1',
    messagingSenderId: '642502995428',
    projectId: 'full-crud-application',
    storageBucket: 'full-crud-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPLgGUth9qvKyF8mky_4v-dm2sHTTYH4o',
    appId: '1:642502995428:ios:b373e33364bc8fa6686bf1',
    messagingSenderId: '642502995428',
    projectId: 'full-crud-application',
    storageBucket: 'full-crud-application.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPLgGUth9qvKyF8mky_4v-dm2sHTTYH4o',
    appId: '1:642502995428:ios:b373e33364bc8fa6686bf1',
    messagingSenderId: '642502995428',
    projectId: 'full-crud-application',
    storageBucket: 'full-crud-application.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbY-0GqHkKardiRV4nImYMYA55lWjLQ9I',
    appId: '1:642502995428:web:574538c9586aa31f686bf1',
    messagingSenderId: '642502995428',
    projectId: 'full-crud-application',
    authDomain: 'full-crud-application.firebaseapp.com',
    storageBucket: 'full-crud-application.firebasestorage.app',
  );
}
